# frozen_string_literal: true

# Gemfile for fastlane (iOS build & release)
# Run: cd ios/fastlane && bundle install
# Then: bundle exec fastlane <lane>

source "https://rubygems.org"

gem "fastlane", "~> 2.225"
gem "cocoapods", "~> 1.16"
gem "xcodeproj", "~> 1.27"
