// Auto-generated by scripts/sync-release-status.mjs.
// Do not edit by hand; rerun npm run sync:release-status after release prechecks.

export const generatedReleaseStatus = {
  "applePrerequisitesReady": false,
  "firstTestFlightBuildUploaded": false,
  "appStoreAssetsReady": true,
  "summary": "Apple Developer / App Store Connect / API Key / GitHub Variables & Secrets 仍待补齐；App Store 素材真值已通过仓库校验，且最近一次专项预检已留下时间戳；首个 TestFlight Build 仍待真实触发；最终触发仓库态仍有 3 个阻塞",
  "triggerTagName": "v0.1.0",
  "triggerGateReady": false,
  "triggerGateFailures": [
    "工作区仍有未提交改动，当前不会安全触发 v0.1.0：M src/data/releaseStatus.generated.ts",
    "本地已存在 v0.1.0 tag，需先人工核对是否沿用、删除重建或改版本号",
    "origin 远端已存在 v0.1.0 tag，当前不会重复触发首个 Build"
  ],
  "assetsValidatedAt": 1780357146976,
  "updatedAt": 1780357147083,
  "preflightReportGeneratedAt": "2026-06-01T23:39:06.976Z",
  "preflightOverallStatus": "FAIL",
  "preflightBlockingCount": 2,
  "preflightFailedChecks": [
    "提测关键测试",
    "TestFlight 输入预检"
  ],
  "preflightSteps": [
    {
      "label": "TypeScript 校验",
      "ok": true,
      "status": 0,
      "durationMs": 1461,
      "stdoutTail": [
        "> AIBrainIM@0.1.0 typecheck",
        "> tsc --noEmit"
      ],
      "stderrTail": []
    },
    {
      "label": "提测关键测试",
      "ok": false,
      "status": 1,
      "durationMs": 2855,
      "stdoutTail": [
        "> AIBrainIM@0.1.0 test:release",
        "> jest --runInBand --detectOpenHandles __tests__/releaseReadiness.test.ts __tests__/releaseChannel.test.ts __tests__/uploadReleaseEvidence.test.ts __tests__/DashboardScreen.test.tsx __tests__/ProfileScreen.test.tsx __tests__/ProjectLibraryScreen.test.tsx __tests__/UploadScreen.test.tsx"
      ],
      "stderrTail": [
        "PASS __tests__/uploadReleaseEvidence.test.ts",
        "Test Suites: 1 failed, 6 passed, 7 total",
        "Tests:       1 failed, 143 passed, 144 total",
        "Snapshots:   0 total",
        "Time:        2.411 s, estimated 3 s",
        "Ran all test suites matching /__tests__\\/releaseReadiness.test.ts|__tests__\\/releaseChannel.test.ts|__tests__\\/uploadReleaseEvidence.test.ts|__tests__\\/DashboardScreen.test.tsx|__tests__\\/ProfileScreen.test.tsx|__tests__\\/ProjectLibraryScreen.test.tsx|__tests__\\/UploadScreen.test.tsx/i."
      ]
    },
    {
      "label": "TestFlight 输入预检",
      "ok": false,
      "status": 1,
      "durationMs": 82,
      "stdoutTail": [
        "> bash scripts/validate-testflight-inputs.sh",
        "ERROR: both ASC_KEY_ID and APPLE_API_KEY_ID are empty",
        "ERROR: both ASC_ISSUER_ID and APPLE_API_ISSUER_ID are empty",
        "ERROR: APPLE_TEAM_ID is empty",
        "ERROR: APPLE_API_KEY_CONTENT is empty",
        "Required Apple CI configuration is incomplete."
      ],
      "stderrTail": []
    },
    {
      "label": "发布配置校验",
      "ok": true,
      "status": 0,
      "durationMs": 91,
      "stdoutTail": [
        "OK: validate:trigger-readiness: blocks duplicate local v0.1.0 tag before push",
        "OK: validate:trigger-readiness: blocks duplicate or unverified remote v0.1.0 tag before push",
        "OK: package.json: engines.node >= 22.11.0",
        "OK: CI workflow: NODE_VERSION pinned to 22",
        "OK: TestFlight workflow: node-version 22",
        "Release config looks consistent."
      ],
      "stderrTail": []
    },
    {
      "label": "App Store 素材校验",
      "ok": true,
      "status": 0,
      "durationMs": 89,
      "stdoutTail": [
        "MISSING: fastlane/metadata/App Store Connect/iPhone 6.5 - 3.png (will be flagged by App Store Connect)",
        "MISSING: fastlane/metadata/App Store Connect/AppIcon.png",
        "OK: ios/AIBrainIM/Images.xcassets/AppIcon.appiconset/Contents.json",
        "Screenshots: 0/6",
        "AppIcon: present",
        "App Store asset check complete (TestFlight - non-blocking)."
      ],
      "stderrTail": []
    }
  ],
  "preflightNextActions": [
    "先修复提测关键测试失败项，再重新跑 npm run test:release。",
    "先补 Apple Developer / App Store Connect / API Key / GitHub Variables & Secrets，再重新跑 npm run preflight:testflight。",
    "上传提测真值仍未闭合：当前没有可复用的 LIVE done 样本，先补一条真实附件回流后再触发首个 Build。",
    "先清理 trigger:testflight 的仓库态阻塞（脏工作区 / 重复 tag / 远端 tag 状态不明），再触发首个 Build。"
  ],
  "activeUploads": 0,
  "completedUploads": 0,
  "liveCompletedUploads": 0,
  "simulatedCompletedUploads": 0,
  "liveDispatchedOnlyUploads": 0,
  "uploadEvidenceSummary": "LIVE完成 0 · LIVE仅分派 0 · 模拟完成 0 · 处理中 0 · 提测真值 尚无样本",
  "missingAppleInputs": [
    "ASC_KEY_ID/APPLE_API_KEY_ID",
    "ASC_ISSUER_ID/APPLE_API_ISSUER_ID",
    "APPLE_TEAM_ID",
    "APPLE_API_KEY_CONTENT"
  ],
  "validationDetails": {
    "version": "0.1.0",
    "apple": "Missing Apple inputs: ASC_KEY_ID/APPLE_API_KEY_ID, ASC_ISSUER_ID/APPLE_API_ISSUER_ID, APPLE_TEAM_ID, APPLE_API_KEY_CONTENT",
    "assets": "ok",
    "preflight": "仍有 2 个提测阻塞：提测关键测试、TestFlight 输入预检。 | 上传提测真值：LIVE完成 0 · LIVE仅分派 0 · 模拟完成 0 · 处理中 0 · 提测真值 尚无样本 | trigger:testflight 门禁：工作区仍有未提交改动，当前不会安全触发 v0.1.0：M src/data/releaseStatus.generated.ts；本地已存在 v0.1.0 tag，需先人工核对是否沿用、删除重建或改版本号；origin 远端已存在 v0.1.0 tag，当前不会重复触发首个 Build"
  }
} as const;
