// Auto-generated by scripts/sync-release-status.mjs.
// Do not edit by hand; rerun npm run sync:release-status after release prechecks.

export const generatedReleaseStatus = {
  "applePrerequisitesReady": true,
  "firstTestFlightBuildUploaded": false,
  "appStoreAssetsReady": true,
  "summary": "Apple / TestFlight 前置项已通过本地结构校验并完成最近一次总预检；App Store 素材真值已通过仓库校验并完成最近一次总预检；首个 TestFlight Build 仍待真实触发；最终触发仓库态仍有 2 个阻塞",
  "triggerTagName": "v0.8.2",
  "triggerGateReady": false,
  "triggerGateFailures": [
    "本地已存在 v0.8.2 tag，需先人工核对是否沿用、删除重建或改版本号",
    "origin 远端已存在 v0.8.2 tag，当前不会重复触发首个 Build"
  ],
  "validatedAt": 1782485097661,
  "assetsValidatedAt": 1782485097661,
  "updatedAt": 1782485097816,
  "preflightReportGeneratedAt": "2026-06-26T14:44:57.661Z",
  "preflightOverallStatus": "PASS",
  "preflightBlockingCount": 0,
  "preflightFailedChecks": [],
  "preflightSteps": [
    {
      "label": "TypeScript 校验",
      "ok": true,
      "status": 0,
      "durationMs": 2094,
      "stdoutTail": [
        "> AIBrainIM@0.8.2 typecheck",
        "> tsc --noEmit"
      ],
      "stderrTail": []
    },
    {
      "label": "TestFlight 输入预检",
      "ok": true,
      "status": 0,
      "durationMs": 106,
      "stdoutTail": [
        "> AIBrainIM@0.8.2 validate:testflight",
        "> bash scripts/validate-testflight-inputs.sh",
        "Apple CI inputs look present and structurally valid."
      ],
      "stderrTail": []
    },
    {
      "label": "发布配置校验",
      "ok": true,
      "status": 0,
      "durationMs": 99,
      "stdoutTail": [
        "OK: validate:trigger-readiness: blocks duplicate local v0.1.0 tag before push",
        "OK: validate:trigger-readiness: blocks duplicate or unverified remote v0.1.0 tag before push",
        "OK: package.json: engines.node >= 22.11.0",
        "OK: CI workflow: NODE_VERSION pinned to 22",
        "OK: TestFlight workflow: node-version 22",
        "Release config looks consistent."
      ],
      "stderrTail": []
    },
    {
      "label": "App Store 素材校验",
      "ok": true,
      "status": 0,
      "durationMs": 99,
      "stdoutTail": [
        "MISSING: fastlane/metadata/App Store Connect/iPhone 6.5 - 3.png (will be flagged by App Store Connect)",
        "MISSING: fastlane/metadata/App Store Connect/AppIcon.png",
        "OK: ios/AIBrainIM/Images.xcassets/AppIcon.appiconset/Contents.json",
        "Screenshots: 0/6",
        "AppIcon: present",
        "App Store asset check complete (TestFlight - non-blocking)."
      ],
      "stderrTail": []
    }
  ],
  "preflightNextActions": [
    "可以继续执行 npm run trigger:testflight；脚本会先复跑总预检、再校验触发门禁，最后才打 v0.1.0 tag 并 push。",
    "确认 GitHub Actions TestFlight workflow 正常归档并上传。",
    "到 App Store Connect 的 TestFlight 页面添加测试人员并做真机安装验证。",
    "上传提测真值仍未闭合：当前没有可复用的 LIVE done 样本，先补一条真实附件回流后再触发首个 Build。",
    "先清理 trigger:testflight 的仓库态阻塞（脏工作区 / 重复 tag / 远端 tag 状态不明），再触发首个 Build。"
  ],
  "activeUploads": 0,
  "completedUploads": 0,
  "liveCompletedUploads": 0,
  "simulatedCompletedUploads": 0,
  "liveDispatchedOnlyUploads": 0,
  "uploadEvidenceSummary": "LIVE完成 0 · LIVE仅分派 0 · 模拟完成 0 · 处理中 0 · 提测真值 尚无样本",
  "validationDetails": {
    "version": "0.8.2",
    "apple": "ok",
    "assets": "ok",
    "preflight": "代码、测试、Apple 前置项、发布配置与 App Store 素材校验均已通过。 | 上传提测真值：LIVE完成 0 · LIVE仅分派 0 · 模拟完成 0 · 处理中 0 · 提测真值 尚无样本 | trigger:testflight 门禁：本地已存在 v0.8.2 tag，需先人工核对是否沿用、删除重建或改版本号；origin 远端已存在 v0.8.2 tag，当前不会重复触发首个 Build"
  }
} as const;
